# CZ1104 Linear Lab 3
---
Import all the Necessary Packages

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import string
import math
from fractions import Fraction
from scipy import linalg

## Problem 1

#### Echelon Form
Follow step by step, and code the echelon form method stated below. (Read the step by step account below). Use  your code to test out some matrices and see if they reduce it to echelon form. Because floats are cumbersome to deal with, I allow you to code with entries in GF(2), i.e. entries with only 0s and 1s

### Sorting Rows by Position of the Leftmost Nonzero

In [3]:
def echelon_form(rowlist):
    new_rowlist = []
    rows_left = set(range(len(rowlist)))
    col_label_list = rowlist.shape[1];
    
    for c in range (col_label_list):
        rows_with_nonzero = [r for r in rows_left if rowlist[r][c]!=0]
        
        if rows_with_nonzero!=[]:
            pivot = rows_with_nonzero[0]
            rows_left.remove(pivot)
            new_rowlist.append(rowlist[pivot])
        
        for r in rows_with_nonzero[1:]:
            multiplier = rowlist[r][c]/rowlist[pivot][c]
            rowlist[r] = rowlist[r] - multiplier * rowlist[pivot]
            
    for r in rows_left:
        new_rowlist.append(rowlist[r])
        
    return new_rowlist
        

In [4]:
matrix1 = np.vstack([[0,0,1,1],
         [1,0,1,1],
         [1,0,0,1],
         [1,1,1,1]])

matrixd = np.array(echelon_form(matrix1))
print(matrixd)

[[1 0 1 1]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 0 1]]


## Problem 2(a) Based on Announcement

Useing ech form to solve system of equations (you cook up some equations)

Define a Matrix A and Matrix B to work with

In [5]:
matrixA = np.vstack([[2,3,4],[1,2,3],[1,4,5]]).astype(float)
matrixB = np.vstack([[1],[1],[2]]).astype(float)

Function for backward substituition

In [6]:
def backward_sub(a,b):
    n = b.size
    x = np.zeros(n)
    x[n-1] = b[n-1]/a[n-1,n-1]
    for i in range (n-2, -1, -1):
        value = 0
        for j in range (i+1, n):
            value += a[i,j]*x[j]
        
        x[i] = (b[i] - value)/a[i,i]
    
    return (x)

Form the Augmented Matrix A and B

In [7]:
AugMat = np.concatenate((matrixA,matrixB), axis = 1)
print('Augmented Matrix:')
for i, col in enumerate(AugMat):
    print(col)

Augmented Matrix:
[2. 3. 4. 1.]
[1. 2. 3. 1.]
[1. 4. 5. 2.]


Perform the echelon form using the function in Q1

In [8]:
echfmatrix = np.array(echelon_form(AugMat))
print('Echelon Form Matrix:')
for i, col in enumerate(echfmatrix):
    print(col)

Echelon Form Matrix:
[2. 3. 4. 1.]
[0.  0.5 1.  0.5]
[ 0.  0. -2. -1.]


Extract B last index out the Echelon form matrix

In [9]:
B = []
for i, col in enumerate(echfmatrix):
    B.append(col[echfmatrix.shape[1]-1])

B = np.vstack(B)
A = np.delete(echfmatrix,echfmatrix.shape[1]-1, axis =1)

Find X matrix

In [10]:
print("By Backward Substitution, X is:")
X = backward_sub(A,B)
print(X)

By Backward Substitution, X is:
[-0.5  0.   0.5]


# Problem 2(b)

In [38]:
def echelon_form1(rowlist):
    new_rowlist = []
    rows_left = set(range(len(rowlist)))
    col_label_list = rowlist.shape[1];
    
    for c in range (col_label_list):
        rows_with_nonzero = [r for r in rows_left if rowlist[r][c]!=0]
        
        if rows_with_nonzero!=[]:
            pivot = rows_with_nonzero[0]
            rows_left.remove(pivot)
            new_rowlist.append(rowlist[pivot])
        
        for r in rows_with_nonzero[1:]:
            multiplier = rowlist[r][c]/rowlist[pivot][c]
            multiplier_one = np.multiply(rowlist[pivot], multiplier)
            multiplier1_frac = [Fraction((x)) for x in multiplier_one]
            
            for i, a in enumerate(rowlist[r]):
                if multiplier1_frac[i].denominator != 1:
                    rowlist[r][i] = a - multiplier1_frac[i]
                else:
                    rowlist[r][i] = a - multiplier1_frac[i].numerator

            
    for r in rows_left:
        new_rowlist.append(rowlist[r])
        
    return new_rowlist
        

In [41]:
matrix = np.array([[0,2,3,4,5],[0,0,0,3,2],[1,2,3,4,5],[0,0,0,6,7],[0,0,0,9,8]],dtype=float)
echformmat = echelon_form1(matrix)
print(np.vstack(echformmat))

[[1. 2. 3. 4. 5.]
 [0. 2. 3. 4. 5.]
 [0. 0. 0. 3. 2.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]]
