# CZ1104 Lab 4

------------------------------------------------------------------------------

In [1]:
import numpy as np
from math import sqrt
from decimal import Decimal as Dec

### Question 1

#### a

Write a program to test if a set of vectors {v1,v2,…,vn} is an orthogonal set.

In [2]:
def isOrthogonal(A):
    flag = 0
    for i in range(len(A[0])):
        col1 = A[:, i]
        dotprod = 0
        for j in range(i, len(A[0])):
            if(i == j):
                continue
            col2 = A[:, j]
            dotprod = np.transpose(col1).dot(col2)
            if(dotprod != 0):
                print(">> Given matrix is NOT orthogonal")
                print(">> Non-Orthogonal pairs: vector " + str(i+1) + " & vector "+ str(j+1))
                flag = 1
                break
        if(flag == 1):
            break
    if (flag == 0):
        print(">> Given matrix is orthogonal")

X = np.array([[1, 0, 0],
            [0, 1, 0],
            [0, 0, 1]])

Y = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

print("--------------- TESTING OF orthogonal(A) FUNCTION ---------------")
print()
print("Given test matrix 1:")
print(X)
print()
print("Orthogonality test result:")
isOrthogonal(X)
print()
print("Given test matrix 2:")
print(Y)
print()
print("Orthogonality test result:")
isOrthogonal(Y)

--------------- TESTING OF orthogonal(A) FUNCTION ---------------

Given test matrix 1:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Orthogonality test result:
>> Given matrix is orthogonal

Given test matrix 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Orthogonality test result:
>> Given matrix is NOT orthogonal
>> Non-Orthogonal pairs: vector 1 & vector 2


#### b

Output which pairs are not orthogonal. Test it for the column vectors of A

In [3]:
import numpy as np

a = np.array([[-6, -3, 6, 1],
            [-1, 2, 1, -6],
            [3, 6, 3, -2],
            [6, -3, 6, -1],
            [2, -1, 2, 3],
            [-3, 6, 3, 2],
            [-2, -1, 2, -3],
            [1, 2, 1, 6]])

isOrthogonal(a)
print()

# print pairs instead of just stating the vector pairs
for j in range(0,len(a[0])):
    for k in range(0,len(a[0])):
        scalar = np.dot(a[:,j],a[:,k].transpose())
        if(scalar != 0): 
            print("Pairs that are not orthogonal:")
            print(a[:,j])
            print(a[:,k])
            print()

>> Given matrix is orthogonal

Pairs that are not orthogonal:
[-6 -1  3  6  2 -3 -2  1]
[-6 -1  3  6  2 -3 -2  1]

Pairs that are not orthogonal:
[-3  2  6 -3 -1  6 -1  2]
[-3  2  6 -3 -1  6 -1  2]

Pairs that are not orthogonal:
[6 1 3 6 2 3 2 1]
[6 1 3 6 2 3 2 1]

Pairs that are not orthogonal:
[ 1 -6 -2 -1  3  2 -3  6]
[ 1 -6 -2 -1  3  2 -3  6]



#### c

Is it always true (in executing program on dot product) that 2 vectors v.w ≠ 0 means v is not orthogonal to w? If it is not necessary true, give an example and propose a fix.

> It is theorically true. But it is not programically true. This is because a float number may be present in the vectors and the dot product may not be 0 (Like lab 3, there are floating point values that have limited precisions that can lead to certain rounding-off or approximation of values that are close to 0).

In [4]:
Z = np.array([[3/sqrt(11), -1/sqrt(6), -1/sqrt(66)],
            [1/sqrt(11),2/sqrt(6), -4/sqrt(66)],
            [1/sqrt(11),1/sqrt(6), 7/sqrt(66)]])


isOrthogonal(Z)
 

>> Given matrix is NOT orthogonal
>> Non-Orthogonal pairs: vector 1 & vector 3


> To solve the issue, `use of the decimal class` to obtain a higher precision of these values, hence showing that it is orthogonal.

In [5]:
a = Dec(sqrt(11))
b = Dec(sqrt(6))
c = Dec(sqrt(66))

Z_solve = np.array([[3/a, -1/b, -1/c],
                    [1/a,2/b, -4/c],
                    [1/a,1/b, 7/c]])

isOrthogonal(Z_solve)

>> Given matrix is orthogonal


### Question 2

Write a module “Orthonormalisation” that defines a a procedure orthonormalise(L) with the following specs:

- Input: a list L of linearly independent Vecs
- Output: a list L* of len(L) orthonormal Vecs such that, for i= 1, 2, …, len(L), the first i Vecs of L* and the first i Vecs of L span the same space.


In [6]:
def projectionV(vec1, vec2):
    dotdiv = (vec1@vec2)/(vec2@vec2)
    proj = dotdiv * vec2
    return proj

def orthoNormal(matrix):
    
    tmatrix = np.array(matrix)
    n = len(matrix)
    proj_x = 0
    
    for i in range (1,n):
        for j in range(i):
            proj_x = proj_x + projectionV(tmatrix[i],tmatrix[j])
        ovec = np.subtract(tmatrix[i], proj_x)
        tmatrix[i] = ovec
        proj_x = 0
    
    for i in range(n):
        mag = sqrt(tmatrix[i] @ tmatrix[i])
        tmatrix[i] = tmatrix[i] / mag
        
    
    return tmatrix.T

In [7]:
orth_test_list = np.array([[4,3,1,2],[8,9,-5,-5],[10,1,-1,5]],dtype=float)

print("Original Matrix:")
print(orth_test_list)
print()
print("Matrix after Orthonormalisation:")
print(orthoNormal(orth_test_list))

Original Matrix:
[[ 4.  3.  1.  2.]
 [ 8.  9. -5. -5.]
 [10.  1. -1.  5.]]

Matrix after Orthonormalisation:
[[ 0.73029674  0.18677078  0.5275409 ]
 [ 0.54772256  0.4027245  -0.6531217 ]
 [ 0.18257419 -0.56614893 -0.51230873]
 [ 0.36514837 -0.69455384  0.18075511]]


### Question 3

#### a

Write a program to compute the QR factorization of matrix A = QR, where Q is orthonormal and R is upper triangular. (refer to lecture notes for the theory). You may assume A consists of linearly independent vectors.

In [8]:
def QR_factorization(matrix):
    mat = matrix
    tmat = matrix.T
    n = tmat.shape[1]
    Qmatrix = orthoNormal(mat)
    Rmatrix = np.zeros((n, n))
    
    QT = Qmatrix.T
    for i in range(n):
        for j in range(i,n):
            Rmatrix[i,j] = QT[i]@ mat[j]
            
    return Qmatrix ,Rmatrix

#### b

Compute the QR factorization of A, formed by the 3 column vectors in Q2.

In [9]:
matrixA = np.array([[4.0, 3.0, 1.0, 2.0],
              [8.0, 9.0, -5.0, -5.0],
              [10.0, 1.0, -1.0, 5.0]])

Q, R = QR_factorization(matrixA)

print("Matrix Q:\n")
print(Q)
print("\n")

print("Matrix R:\n")
print(R)
print("\n")

print("Matrix A:\n")
print((Q @ R).T)
print("\n")

Matrix Q:

[[ 0.73029674  0.18677078  0.5275409 ]
 [ 0.54772256  0.4027245  -0.6531217 ]
 [ 0.18257419 -0.56614893 -0.51230873]
 [ 0.36514837 -0.69455384  0.18075511]]


Matrix R:

[[ 5.47722558  8.03326418  9.49385766]
 [ 0.         11.42220061 -0.63618797]
 [ 0.          0.          6.0383716 ]]


Matrix A:

[[ 4.  3.  1.  2.]
 [ 8.  9. -5. -5.]
 [10.  1. -1.  5.]]


